#!/bin/sh -e

GIT_URL="$1"

sed -E -e "s@/cgit.css@cgit.css@" \
    -e "s@<th class='left'><a href='/\?s=(idle|owner)'>(Idle|Owner)</a></th>@@g" \
    -e "s@<a href='/\?s=[^']+'>([^<]+)</a>@\1@g" \
    -e "s@/openinkpot.png@openinkpot.png@" \
    -e "s@/cgit.png@openinkpot.png@" \
    -e "s@<a class='active' href='/'>index.*\$@@" \
    -e "s@^<input.*\$@@" \
    -e "s@</form>.*\$@@" \
    -e "s@<td>(Mikhail Gusarov|Vadim Lopatin|Alexander Kerner|Yauhen Kharuzhy|Alexander Nikolaev|Ondřej Herman|Alexey Zaytsev|Evan Kroske)</td>@@" \
    -e "s@<td><span class='age-(years|months)'>[^<]+</span></td>@@" \
    -e "s@href='/([^']+\.git)/'@href='$GIT_URL\1'@g" \
    -e "s@<div class='footer'>.*@@"
  
